# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

#name: Produce PDFs

#on:
  #[ push ]

#jobs:
  #pdfs:

    #runs-on: ubuntu-latest

    #steps:
    #- uses: actions/checkout@v2
    #- name: Set up Python 3.8
      #uses: actions/setup-python@v2
      #with:
        #python-version: 3.8
    #- name: Install dependencies
      #run: |
        #python -m pip install --upgrade pip
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    #- name: XML testing
      #run: |
        #python -m unittest tests.TestXmlLoad.test_file_load
    #- name: Produce PDF files
      #run: |
        #sudo apt-get install wkhtmltopdf
        #echo "Set up remote"
        #git remote set-url origin $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
        #echo "Fetch master"
        #git fetch
        #echo "Check out HEAD branch"
        #git checkout $GITHUB_HEAD_REF
        #echo "Get diff from master"
        #git diff --name-status origin/master xmls/ > git_files.txt
        #echo "Produce PDF files"
        #python -m unittest tests.TestXmlLoad.test_produce_new_pdfs
        #echo "Get status"
        #git status
        #echo "Tell git who I am"
        #git config --local user.email "action@github.com"
        #git config --local user.name "GitHub Action"
        #echo "Add new files"
        #git add pdfs/
        #echo "Commit"
        #git commit -m "Auto update of PDF files according to changes in XMLs"
        #echo "Push"
        #git push origin $GITHUB_HEAD_REF
